# Generated by Django 4.1 on 2022-12-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=70)),
                ('point1', models.CharField(max_length=70)),
                ('point2', models.CharField(max_length=70)),
                ('point3', models.CharField(max_length=70)),
                ('point4', models.CharField(max_length=70)),
                ('point5', models.CharField(max_length=70)),
                ('comment', models.CharField(max_length=1000)),
            ],
        ),
    ]
