# Generated by Django 4.1 on 2023-01-02 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_topup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopUpRequest',
        ),
    ]
