# Generated by Django 4.1 on 2023-01-02 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_delete_topuprequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='balance',
        ),
    ]
