# Generated by Django 4.1 on 2022-12-30 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='hall',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='movie',
        ),
        migrations.AddField(
            model_name='movieschedule',
            name='reserved_seats',
            field=models.ManyToManyField(blank=True, to='core.seat'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='seats',
            field=models.ManyToManyField(blank=True, to='core.seat'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='slots',
            field=models.ManyToManyField(blank=True, to='core.slot'),
        ),
        migrations.AlterField(
            model_name='movieschedule',
            name='hall',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.hall'),
        ),
        migrations.AlterField(
            model_name='movieschedule',
            name='movie',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.movie'),
        ),
    ]
