# Generated by Django 4.1 on 2022-12-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_ticket_hall_remove_ticket_movie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieschedule',
            name='selected_seats',
            field=models.ManyToManyField(blank=True, related_name='selected_seats', to='core.seat'),
        ),
    ]
