# Generated by Django 4.1 on 2022-11-04 17:39

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_movie_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating_average',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=2, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
