# Generated by Django 4.1 on 2022-12-31 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_movieschedule_selected_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='balance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, null=True),
        ),
    ]
