# Generated by Django 4.1 on 2022-11-06 13:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_slot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
