# Generated by Django 4.1 on 2022-12-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_transaction_remove_movie_price_delete_checkout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='movies',
        ),
        migrations.AddField(
            model_name='transaction',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tickets',
            field=models.ManyToManyField(to='core.ticket'),
        ),
    ]
