# Generated by Django 4.1 on 2022-11-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_movie_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='thumbnail',
            field=models.FileField(null=True, upload_to='thumbnail'),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.FileField(null=True, upload_to='movies'),
        ),
    ]
