# Generated by Django 4.1 on 2022-11-05 19:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_movie_release_date_movie_thumbnail_movie_trailer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=20)),
                ('discount', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('count', models.IntegerField(default=0)),
                ('ends_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('slot', models.CharField(choices=[('8:00', '8:00'), ('11:00', '11:00'), ('14:00', '14:00'), ('17:00', '17:00'), ('20:00', '20:00'), ('23:00', '23:00')], default='8:00', max_length=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='movieschedule',
            name='price',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='discount',
        ),
        migrations.AddField(
            model_name='movie',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='discount',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.coupon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hall',
            name='slots',
            field=models.ManyToManyField(to='core.slot'),
        ),
        migrations.AddField(
            model_name='movieschedule',
            name='slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.slot'),
        ),
    ]
