# Generated by Django 4.1 on 2022-12-31 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_ticket_playtime_remove_ticket_seat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='seats',
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.seat'),
        ),
    ]
