# Generated by Django 4.1 on 2022-12-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_name_movie_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='thumbnail',
            field=models.FileField(default='undefined', upload_to='thumbnail'),
        ),
    ]
