# Generated by Django 4.1 on 2022-11-05 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_movieschedule_playtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='venue',
        ),
    ]
