# Generated by Django 4.1 on 2023-01-01 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_topup_is_approved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topup',
        ),
    ]
