# Generated by Django 4.1 on 2023-01-02 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delete_topup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='movies',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='rating_average',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='rating_count',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='reviews',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
    ]
