# Generated by Django 4.1 on 2023-01-02 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_venue_movies_remove_movie_rating_average_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('Running', 'Running'), ('Upcoming', 'Upcoming'), ('Archived', 'Archived')], default='Archived', max_length=10),
        ),
    ]
