# Generated by Django 4.1 on 2023-01-03 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_ticket_is_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieschedule',
            name='selected_seats',
        ),
    ]
